# Generated by Django 5.2.3 on 2025-07-13 13:22

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('vacation', 'إجازة')], default='present', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الحضور'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.employee_image_path, verbose_name='صورة الموظف'),
        ),
    ]
