# Generated by Django 5.2.3 on 2025-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.FloatField(default=0.0, editable=False, verbose_name='ساعات العمل'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['working_hours'], name='employees_a_working_eb1a30_idx'),
        ),
    ]
