# Generated by Django 5.2.3 on 2025-06-30 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_salarypayment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
