# Generated by Django 5.2.3 on 2025-07-01 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_salarypayment_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='المدير المسؤول'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to='employees.employee', verbose_name='وافق عليه'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(verbose_name='وقت الحضور'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='حاضر'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('FT', 'دوام كامل'), ('PT', 'دوام جزئي'), ('CT', 'عقد')], default='FT', max_length=2, verbose_name='نوع التوظيف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='actual_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الفعلي'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='working_days',
            field=models.PositiveIntegerField(default=0, verbose_name='أيام العمل'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='year',
            field=models.PositiveIntegerField(verbose_name='السنة'),
        ),
    ]
