# Generated by Django 5.2.3 on 2025-07-12 14:02

import django.core.validators
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_manager_salarypayment_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee'], 'verbose_name': 'حضور', 'verbose_name_plural': 'سجلات الحضور'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-year', '-month', 'employee'], 'verbose_name': 'دفع الراتب', 'verbose_name_plural': 'مدفوعات الرواتب'},
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.employee_image_path, verbose_name='صورة الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='actual_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الفعلي'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='working_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='أيام العمل'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='السنة'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='salarypayment',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
